import {
  FaAt,
  FaLock,
  FaPlus,
  FaEye,
  FaTrashAlt,
  FaChartLine,
  FaBookReader,
  FaBook,
  FaDotCircle,
  FaFile,
  FaTrash,
  FaFacebookF,
  FaTwitter,
  FaLinkedinIn,
  FaYoutube,
  FaMapMarkerAlt,
  FaChalkboardTeacher,
  FaHandsHelping,
} from "react-icons/fa";
import {
  BiChevronDown,
  BiChevronUp,
  BiEnvelope,
  BiPhone,
  BiUser,
  BiCheck,
  BiPhoneCall,
  BiArrowBack,
  BiLoader,
} from "react-icons/bi";
import {
  MdOutlineDashboard,
  MdOutlineArrowBackIos,
  MdOutlineArrowForwardIos,
  MdOutlineCancel,
  MdOutlineUpdate,
  MdOutlinePhotoCamera,
  MdHelpOutline,
  MdOutlineMessage,
  MdAttachFile,
  MdOutlineMoreVert,
  MdFavoriteBorder,
  MdFavorite,
  MdMenuBook,
  MdFreeBreakfast,
  MdKeyboardDoubleArrowLeft,
  MdKeyboardDoubleArrowRight,
} from "react-icons/md";
import { Si1Password, SiChartdotjs } from "react-icons/si";
import {
  IoArrowBack,
  IoSearch,
  IoNotificationsOutline,
  IoHelp,
  IoLogOut,
  IoBasketOutline,
  IoCubeOutline,
  IoSettingsOutline,
  IoPrint,
  IoCheckmarkDone,
  IoCloseOutline,
} from "react-icons/io5";
import { FiUsers, FiUser, FiLogOut } from "react-icons/fi";
import {
  BsSliders,
  BsEmojiSmile,
  BsFolderFill,
  BsFolderSymlinkFill,
  BsLink45Deg,
  BsStarFill,
  BsStarHalf,
  BsStar,
  BsEyeSlash,
  BsEye,
  BsCapsule,
  BsPinAngle,
  BsFillCameraFill,
  BsCloudUploadFill,
  BsCloudDownloadFill,
  BsFillFileEarmarkPdfFill,
  BsTrash,
} from "react-icons/bs";
import { RiSendPlaneFill, RiAttachment2 } from "react-icons/ri";
import { SiGoogleclassroom } from "react-icons/si";
import { VscDebugStart } from "react-icons/vsc";
import {
  HiDocumentArrowDown,
  HiOutlineDocumentDuplicate,
} from "react-icons/hi2";
import { LuPlane } from "react-icons/lu";

export {
  FaFile,
  FaTrash,
  FaAt,
  FaLock,
  FaEye,
  FaPlus,
  FaTrashAlt,
  FaChartLine,
  FaBookReader,
  FaBook,
  FaDotCircle,
  FaFacebookF,
  FaTwitter,
  FaLinkedinIn,
  FaYoutube,
  FaMapMarkerAlt,
  FaChalkboardTeacher,
  FaHandsHelping,
  FiUsers,
  FiUser,
  FiLogOut,
  BiChevronDown,
  BiChevronUp,
  BiEnvelope,
  BiPhone,
  BiUser,
  BiCheck,
  BiPhoneCall,
  BiArrowBack,
  BiLoader,
  BsSliders,
  BsEmojiSmile,
  BsFolderFill,
  BsFolderSymlinkFill,
  BsLink45Deg,
  BsStarFill,
  BsStarHalf,
  BsStar,
  BsEyeSlash,
  BsEye,
  BsCapsule,
  BsPinAngle,
  BsFillCameraFill,
  BsCloudUploadFill,
  BsCloudDownloadFill,
  BsFillFileEarmarkPdfFill,
  BsTrash,
  MdOutlineDashboard,
  MdOutlineArrowBackIos,
  MdOutlineArrowForwardIos,
  MdOutlineCancel,
  MdOutlineUpdate,
  MdOutlinePhotoCamera,
  MdHelpOutline,
  MdOutlineMessage,
  MdAttachFile,
  MdOutlineMoreVert,
  MdFavoriteBorder,
  MdFavorite,
  MdMenuBook,
  MdFreeBreakfast,
  MdKeyboardDoubleArrowLeft,
  MdKeyboardDoubleArrowRight,
  Si1Password,
  SiChartdotjs,
  IoArrowBack,
  IoSearch,
  IoHelp,
  IoLogOut,
  IoBasketOutline,
  IoCubeOutline,
  IoSettingsOutline,
  IoNotificationsOutline,
  IoPrint,
  IoCheckmarkDone,
  IoCloseOutline,
  RiSendPlaneFill,
  RiAttachment2,
  SiGoogleclassroom,
  VscDebugStart,
  HiDocumentArrowDown,
  HiOutlineDocumentDuplicate,
  LuPlane,
};
